name: CD
run-name: "CD #${{ github.run_number }} (${{github.sha}})"

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/server
          chmod 600 ~/.ssh/server
          cat > ~/.ssh/config <<END
          Host server
            HostName $SSH_HOST
            User $SSH_USERNAME
            IdentityFile ~/.ssh/server
            PubkeyAuthentication yes
            ChallengeResponseAuthentication no
            PasswordAuthentication no
            StrictHostKeyChecking no
          END
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Run commands
        run: |
          ssh server <<END
          cd $PATH_TO_PROJECT
          git pull
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          END
        env:
          PATH_TO_PROJECT: ${{ secrets.PATH_TO_PROJECT }}

      - name: Composer installing
        run: |
          ssh server <<END
          cd $PATH_TO_PROJECT
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          php artisan key:generate
          chmod -R 777 storage bootstrap/cache
          php artisan migrate
          php artisan l5-swagger:generate
          END
        env:
          PATH_TO_PROJECT: ${{ secrets.PATH_TO_PROJECT }}

      - name: Upgrade
        run: |
          ssh server <<END
          cd $PATH_TO_PROJECT
          php artisan key:generate
          chmod -R 777 storage bootstrap/cache
          php artisan migrate
          php artisan l5-swagger:generate
          END
        env:
          PATH_TO_PROJECT: ${{ secrets.PATH_TO_PROJECT }}
