name: CD
run-name: "CD #${{ github.run_number }} (${{github.sha}})"

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USERNAME
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Run commands
        run: |
          cd ${{ secrets.PATH_TO_PROJECT }}
          git pull
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          php artisan key:generate
          chmod -R 777 storage bootstrap/cache
          php artisan migrate
          php artisan l5-swagger:generate

# jobs:
#   Deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Main workflow
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: ${{ secrets.SSH_USERNAME }}
#           password: ${{ secrets.SSH_PASSWORD }}
#           port: ${{ secrets.SSH_PORT }}
#           script: |
#             cd ${{ secrets.PATH_TO_PROJECT }}
#             git pull
#             php -r "file_exists('.env') || copy('.env.example', '.env');"
#             composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
#             php artisan key:generate
#             chmod -R 777 storage bootstrap/cache
#             php artisan migrate
#             php artisan l5-swagger:generate

